import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="pt-[60px] flex flex-col min-h-[100vh]">
        <header
          className={clsx(
            "text-white flex gap-4 text-center justify-center text text-5l fixed",
            "fixed top-0 lef-0 w-full text-white",
            "h-[60px]"
          )}
        >
          <div className="flex justify-between items-center p-4 h-[60px] gap-4">
            <Link
              href="/"
              className="hover:scale-110 transform transition-transform duration-200 ease-in-out"
            >
              HOME
            </Link>
            <Link
              href="/blog"
              className="hover:scale-110 transform transition-transform duration-200 ease-in-out"
            >
              BLOG
            </Link>
            <Link
              href="/about"
              className="hover:scale-110 transform transition-transform duration-200 ease-in-out"
            >
              ABOUT
            </Link>
            <Link
              href="/playlist"
              className="hover:scale-110 transform transition-transform duration-200 ease-in-out"
            >
              PLAYLIST
            </Link>
          </div>
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
